language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

jdk:
  - oraclejdk8

env:
  global:
  - secure: "SGO9NiZHdPlAwm9qHirXz5lCx1462Ch/MgvKK9TGJDzsmea414TRucHCmL17a+shsLtt/iXE4whikKBcTY4b493wtXYbC5EzZrVb5QKA1XEdjfgbnESov6DLVS85waO/K0GBScmyu02YOC/0ZCShcXrQZpJ0ssK9eMM/jXdTLsQ="
  - secure: "YGgXcGko6RzcA242xa/AMXp0/kujud8QeJxCOQFo1Tt00hSt1Ew8r/LY1h4pW7KB/jmYrebHkMHrTTp/NXN9sjjnWj61NWLwIAEUjEJjJmoZYpaWIar9Aw3QZvp7fngslEp2uJ/v61x2YfCygdCQKlpNEU7GEJMlbC5C/sz7rPo="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
